### ISSUE TITLE
Docente --> Practicas

### ISSUE THREAD

**Issue by angel-94** [angel-94/CALIFICACIONES#12]
![captura4](https://user-images.githubusercontent.com/20443321/29912159-53af2330-8df6-11e7-8d0b-42e7eb602d13.PNG)

Cuado agrego una nueva planeacion con esa practica dentro de las sedes no me aparece la opcion de la UNSIS para realizar el mismo flujo que seguiste y encontrar ese error

**Comment by l-mario** [comment]
Ammmmmm?????'

**Comment by l-mario** [comment]
¿Con cuál práctica?

**Comment by l-mario** [comment]
¿Agregar una planeación dentro de las sedes?
