### ISSUE TITLE
Agregar planeación

### ISSUE THREAD

**Issue by l-mario** [angel-94/CALIFICACIONES#17]
![captura de pantalla de 2017-09-05 11-53-58](https://user-images.githubusercontent.com/22987746/30072757-f2a375ca-9230-11e7-86a8-7397de525e99.png)

* ¿Qué pasa cuando quiera agregar una planeaciónn del ciclo escolar 2017-2018, y una del 2018-2019?

**Comment by l-mario** [comment]
* Debe dejar seleccionar ciclo, 2017-2018, 2018-2019, 2019-2020...
*Si selecciono 2018-2019, los periodos escolar que me deben ser los periodos A y B de ciclo escolar

**Comment by angel-94** [comment]
El periodo escolar se selecciona en base al ciclo escolar y si servicios escolares ya ha dado de alta el ciclo escolar en la pantalla de curso y los periodos escolares correspondientes a ese ciclo ahi apareceran esos periodos escolares
