### ISSUE TITLE
Campos FechaInicio- FechaFin

### ISSUE THREAD

**Issue by l-mario** [angel-94/CALIFICACIONES#19]
![captura de pantalla de 2017-09-05 12-01-32](https://user-images.githubusercontent.com/22987746/30073062-0d8bd12e-9232-11e7-8a20-198f823794d7.png)

* Poner un ejemplo de como es el formato de fecha al agregar una nueva planeacion

**Comment by l-mario** [comment]
![captura de pantalla de 2017-09-05 12-03-46](https://user-images.githubusercontent.com/22987746/30073124-4b08e4e2-9232-11e7-89ac-57866cc601f0.png)

* Me deja agregar la misma fecha

**Comment by l-mario** [comment]
![captura de pantalla de 2017-09-05 12-06-41](https://user-images.githubusercontent.com/22987746/30073229-b6ecd506-9232-11e7-9d9e-ea11dfd381c0.png)
*SI lo agrega

**Comment by angel-94** [comment]
![111](https://user-images.githubusercontent.com/20443321/30094540-8b4839bc-9292-11e7-96a1-013e94ad9205.png)

Awqui puedes ver cual es el formto que pide la fecha cuando se inserta solo acepta fecha no se como es que te permitio escribir "HOLA"

Pero aunque ese formato se ve al introducir el periodo en la base de datos se almacena yyyy-mm-dd

**Comment by angel-94** [comment]
![22222](https://user-images.githubusercontent.com/20443321/30094601-e5b31a8e-9292-11e7-98ab-1d0393634536.png)aHI SE PUEDE VER QUE NO DEJA INSERTAR SI LA FECHA FIN ES MENOR

**Comment by angel-94** [comment]
![3333333](https://user-images.githubusercontent.com/20443321/30094607-f4c80ebc-9292-11e7-81b4-e4d88771f2ac.png)
ahi se puede ver que no deja insertar si las fechas son iguales

**Comment by angel-94** [comment]
![44](https://user-images.githubusercontent.com/20443321/30094619-03be1ccc-9293-11e7-8dec-b88c007779d5.png)
Ahi puedes ver que es una fecha correcta y 
en la siguiente imagen dice que se inseto con exito
![555](https://user-images.githubusercontent.com/20443321/30094634-1164448c-9293-11e7-8bf6-8960b7f2673a.png)
