### ISSUE TITLE
Estudiantes no asignados

### ISSUE THREAD

**Issue by l-mario** [angel-94/CALIFICACIONES#20]
![captura de pantalla de 2017-09-05 12-07-56](https://user-images.githubusercontent.com/22987746/30073308-ea90f266-9232-11e7-9776-bf8fecab136c.png)

* La vista de estudiantes NO asignados si funciona

**Comment by l-mario** [comment]
![captura de pantalla de 2017-09-05 12-08-52](https://user-images.githubusercontent.com/22987746/30073326-0588e0a6-9233-11e7-90d1-a4f7b29c2863.png)

* Aqui ya no van a ver otro periodo , ¿o sí?
* Aqui nisiquiera se maneja periodo

**Comment by angel-94** [comment]
Que emoci[on. si funciona!
