### ISSUE TITLE
Reportes Error 500

### ISSUE THREAD

**Issue by l-mario** [angel-94/CALIFICACIONES#21]
![captura de pantalla de 2017-09-05 12-17-34](https://user-images.githubusercontent.com/22987746/30073669-417d2440-9234-11e7-942f-dd8809d39df8.png)

*¿?

**Comment by angel-94** [comment]
![screenshot from 2017-09-05 23-40-19](https://user-images.githubusercontent.com/20443321/30094733-a318295c-9293-11e7-9c74-79c656670e0e.png)
![screenshot from 2017-09-05 23-40-22](https://user-images.githubusercontent.com/20443321/30094734-a32abc02-9293-11e7-9fb7-5c5a385c82fe.png)


EN LA PRIMER IMAGEN PUEDES VER QUE SON LOS MISMOS DATOS LOS QUE INTRODUJE Y EN ESTA EJCUTANDOSE DESDE TOMCAT ASI QUE ESE ERROR NO LO ENCUENTRO SI TE VUELVE A APOARECER PON UNA IMAGEN DE LA CONSOLA DE CGROME EN EL AOARTADO DE NETWORK MOSTRANDO EL DETALLE DEL ERROR PARA SABER A QUE SE DEBE

**Comment by l-mario** [comment]
No, era por los parámetros de los reportes, eso lo solucioné ayer, se me olvidó quitarlo
