### ISSUE TITLE
Estudiantes

### ISSUE THREAD

**Issue by lMarcoss** [angel-94/CALIFICACIONES#5]
- [ ] Al agregar estudiante, sección información del tutor se aceptan mucha cantidad de número en el campo teléfono
Enlace: http://localhost:8080/#/escolares/estudiante
<img width="1280" alt="captura de pantalla 2017-08-31 a la s 00 05 24" src="https://user-images.githubusercontent.com/16256405/29907318-561d835c-8de0-11e7-89c8-0ff8b6158995.png">

**Comment by angel-94** [comment]
Se aceptan como maximo 30 caracteres
