### ISSUE TITLE
Coordinador -> Asignar sedes

### ISSUE THREAD

**Issue by lMarcoss** [angel-94/CALIFICACIONES#6]
- [ ] No se muestra qué error tengo al intentar assignar sedes
<img width="1280" alt="captura de pantalla 2017-08-31 a la s 00 20 09" src="https://user-images.githubusercontent.com/16256405/29907644-2ada9976-8de2-11e7-9b56-ae9149e2e3eb.png">

**Comment by angel-94** [comment]
Se cambio por combos. Issue cerrado
