### ISSUE TITLE
Coordinador -> Practicantes -> Reportes

### ISSUE THREAD

**Issue by lMarcoss** [angel-94/CALIFICACIONES#7]
???? Error 500???? 
<img width="1280" alt="captura de pantalla 2017-08-31 a la s 00 27 11" src="https://user-images.githubusercontent.com/16256405/29907802-40511a5e-8de3-11e7-83ff-fbbdabcf88ac.png">
Los campos aceptan valores raros
<img width="1280" alt="captura de pantalla 2017-08-31 a la s 00 29 05" src="https://user-images.githubusercontent.com/16256405/29907836-6b9f591e-8de3-11e7-9eba-1bc261b00dc1.png">

**Comment by angel-94** [comment]
Se cambio el periodo escolar a un combo, problema resuelto
